spring:
  config:
    import: "optional:file:../../../.env[.properties]"
  application:
    name: distribution-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${DISTRIBUTION_SERVICE_PORT:8082}

app:
  room-service-url: ${ROOM_SERVICE_URL:http://localhost:8081}
  internal-realtime-token: ${INTERNAL_REALTIME_TOKEN}

management:
  server:
    port: 9082
